name: CI/CD Pipeline
on: 
  workflow_dispatch:
    inputs:
      run_python_ci:
        description: 'Run Python CI (Lint & Test)?'
        type: boolean
        default: true
      run_infrastructure:
        description: 'Run Terraform Infrastructure?'
        type: boolean
        default: false
      run_deployment:
        description: 'Run Build & Deploy (Cloud Run)?'
        type: boolean
        default: false

env:
  PROJECT_ID: ${{ vars.PROD_GCP_PROJECT_ID }}
  WIF_PROVIDER: ${{ vars.PROD_GCP_WIF_PROVIDER }}
  WIF_SA: ${{ vars.PROD_GCP_WIF_SA }}
  REGION: ${{ vars.PROD_GCP_REGION }}

jobs:
  python-ci:
    if: ${{ inputs.run_python_ci == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check cloude_run_service/

      - name: Test with Pytest
        env:
            GOOGLE_CLOUD_PROJECT: "mock-project"
            KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
        run: pytest cloude_run_service/

  infrastructure:
    if: ${{ always() && inputs.run_infrastructure == true && (needs.python-ci.result == 'success' || needs.python-ci.result == 'skipped') }}
    needs: [python-ci]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format & Validate
        run: |
          cd terraform/ 
          terraform init -backend=false
          terraform validate
          terraform apply -auto-approve -input=false

  build-and-deploy:
    if: ${{ always() && inputs.run_deployment == true && (needs.infrastructure.result == 'success' || needs.infrastructure.result == 'skipped') }}
    needs: [infrastructure]
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & Push Ingestion Image
        run: |
          IMAGE_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/mk-docker-repo/ingestion-service:${{ github.sha }}"
                
          if gcloud artifacts docker images describe "$IMAGE_TAG" > /dev/null 2>&1; then
              echo "Image $IMAGE_TAG already exists. Skipping build."
          else
              echo "Image $IMAGE_TAG not found. Proceeding with build..."
              gcloud builds submit cloude_run_service/ --tag "$IMAGE_TAG"
          fi

      - name: Deploy Ingestion to Cloud Run
        run: |
          gcloud run deploy mk-consumer-service \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/mk-docker-repo/ingestion-service:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed

      - name: Build & Push DBT Image
        run: |
          DBT_IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/mk-docker-repo/dbt-job:${{ github.sha }}"
                
          if gcloud artifacts docker images describe "$DBT_IMAGE" > /dev/null 2>&1; then
              echo "DBT Image $DBT_IMAGE already exists. Skipping build."
          else
            echo "DBT Image $DBT_IMAGE not found. Starting Cloud Build..."
            gcloud builds submit dbt/ --tag "$DBT_IMAGE"
          fi

      - name: Update DBT Job Image
        run: |
          gcloud run jobs update mk-dbt-medallion-job \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/mk-docker-repo/dbt-job:${{ github.sha }} \
            --region ${{ env.REGION }}
